#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	float leftEncoder = 0;
	float rightEncoder = 0;
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
	while(true)
	{
		rightEncoder = SensorValue[rightEncoder];
		leftEncoder = SensorValue[leftEncoder];
		writeDebugStreamLine("%.2f%.2f", rightEncoder, leftEncoder);
		delay(500);
	}
}
