#pragma config(Sensor, dgtl1,  twelve,         sensorDigitalIn)
#pragma config(Sensor, dgtl2,  button,         sensorDigitalIn)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  nine,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  nineh,          sensorDigitalIn)
#pragma config(Sensor, dgtl7,  ten,            sensorDigitalIn)
#pragma config(Sensor, dgtl8,  tenh,           sensorDigitalIn)
#pragma config(Sensor, dgtl9,  eleven,         sensorDigitalIn)
#pragma config(Sensor, dgtl10, elevenh,        sensorDigitalIn)
#pragma config(Sensor, dgtl11, leftQuad,       sensorQuadEncoder)
#pragma config(Motor,  port5,           leftFront,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightBack,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightFront,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	float leftQuad = 0;
	float rightQuad = 0;
	SensorValue[rightQuad] = 0;
	SensorValue[leftQuad] = 0;
	while(true)
	{
		rightQuad = SensorValue[rightQuad];
		leftQuad = SensorValue[leftQuad];
		writeDebugStreamLine("%.2f%.2f", rightQuad, leftQuad);
		delay(500);
	}
}
